version = 1
[merge]
method = "squash"

[merge.message]
title = "pull_request_title"
body = "empty"

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[update]
ignored_usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]