services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - postgres
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4_container
#    restart: always
#    networks:
#      - postgres
#    ports:
#      - "8888:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
#      PGADMIN_DEFAULT_PASSWORD: strong-password
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
#  pgadmin-data:

networks:
  postgres:
    driver: bridge